//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BKS {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BKS.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Olay.
        /// </summary>
        internal static string AnahtarTipi_Olay {
            get {
                return ResourceManager.GetString("AnahtarTipi_Olay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personel.
        /// </summary>
        internal static string AnahtarTipi_Personel {
            get {
                return ResourceManager.GetString("AnahtarTipi_Personel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tanımsız.
        /// </summary>
        internal static string AnahtarTipi_Tanimsiz {
            get {
                return ResourceManager.GetString("AnahtarTipi_Tanimsiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Günlük.
        /// </summary>
        internal static string CalismaPlani_Gunluk {
            get {
                return ResourceManager.GetString("CalismaPlani_Gunluk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haftalık.
        /// </summary>
        internal static string CalismaPlani_Haftalik {
            get {
                return ResourceManager.GetString("CalismaPlani_Haftalik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tek Sefer.
        /// </summary>
        internal static string CalismaPlani_TekSefer {
            get {
                return ResourceManager.GetString("CalismaPlani_TekSefer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıtlar siliniyor....
        /// </summary>
        internal static string Delete_Records {
            get {
                return ResourceManager.GetString("Delete_Records", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıtlar Dosyaya Aktarılıyor....
        /// </summary>
        internal static string FileHelper_Export {
            get {
                return ResourceManager.GetString("FileHelper_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıtlar Dosyadan Alınıyor....
        /// </summary>
        internal static string FileHelper_Import {
            get {
                return ResourceManager.GetString("FileHelper_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Okuma Bilgisi Eşleştiriliyor..
        /// </summary>
        internal static string Log_Record_SyncRef {
            get {
                return ResourceManager.GetString("Log_Record_SyncRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt Sil.
        /// </summary>
        internal static string Message_Delete_Head {
            get {
                return ResourceManager.GetString("Message_Delete_Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silme işlemini onaylıyormusunuz ?.
        /// </summary>
        internal static string Message_Delete_Msg {
            get {
                return ResourceManager.GetString("Message_Delete_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilgi.
        /// </summary>
        internal static string Message_Dosya_Head {
            get {
                return ResourceManager.GetString("Message_Dosya_Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu kayıt için özellik aktif değil..
        /// </summary>
        internal static string Message_Dosya_Msg {
            get {
                return ResourceManager.GetString("Message_Dosya_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hata !...
        /// </summary>
        internal static string Message_Error_Head {
            get {
                return ResourceManager.GetString("Message_Error_Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hata.
        /// </summary>
        internal static string Message_Parola_Header {
            get {
                return ResourceManager.GetString("Message_Parola_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parola ve Parola Tekrar aynı olmalıdır..
        /// </summary>
        internal static string Message_Parola_Msg {
            get {
                return ResourceManager.GetString("Message_Parola_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uyari.
        /// </summary>
        internal static string Message_Select_Head {
            get {
                return ResourceManager.GetString("Message_Select_Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt Seçiniz...
        /// </summary>
        internal static string Message_Select_Msg {
            get {
                return ResourceManager.GetString("Message_Select_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başarılı.
        /// </summary>
        internal static string OperasyonStatu_OkumaBasarili {
            get {
                return ResourceManager.GetString("OperasyonStatu_OkumaBasarili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerçekleşmedi.
        /// </summary>
        internal static string OperasyonStatu_OkumaEksik {
            get {
                return ResourceManager.GetString("OperasyonStatu_OkumaEksik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Olay.
        /// </summary>
        internal static string OperasyonStatu_OkumaOlay {
            get {
                return ResourceManager.GetString("OperasyonStatu_OkumaOlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uyarı.
        /// </summary>
        internal static string OperasyonStatu_OkumaUyari {
            get {
                return ResourceManager.GetString("OperasyonStatu_OkumaUyari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planlama.
        /// </summary>
        internal static string OperasyonStatu_Planlama {
            get {
                return ResourceManager.GetString("OperasyonStatu_Planlama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapor Bigileri Okunuyor !...
        /// </summary>
        internal static string Operation_Report {
            get {
                return ResourceManager.GetString("Operation_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devriye planlaması yapılıyor....
        /// </summary>
        internal static string Operation_Schedule {
            get {
                return ResourceManager.GetString("Operation_Schedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devriye puantaj hesaplanıyor....
        /// </summary>
        internal static string Operation_Scoring {
            get {
                return ResourceManager.GetString("Operation_Scoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm senkronizasyon....
        /// </summary>
        internal static string Operation_SyncAlarm {
            get {
                return ResourceManager.GetString("Operation_SyncAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anahtar senkronizasyon....
        /// </summary>
        internal static string Operation_SyncTag {
            get {
                return ResourceManager.GetString("Operation_SyncTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlem iptal edilmiştir.
        /// </summary>
        internal static string ReadTag_Timeout_Header {
            get {
                return ResourceManager.GetString("ReadTag_Timeout_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belitilen süre içinde okuma gerçekleşmedi !...
        /// </summary>
        internal static string ReadTag_Timeout_Message {
            get {
                return ResourceManager.GetString("ReadTag_Timeout_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uyarı.
        /// </summary>
        internal static string ReadTag_Wrn_Header {
            get {
                return ResourceManager.GetString("ReadTag_Wrn_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cihazın bağlantısını kontrol ediniz..
        /// </summary>
        internal static string ReadTag_Wrn_Message {
            get {
                return ResourceManager.GetString("ReadTag_Wrn_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haftanın &quot;{0}&quot; gün/günleri saat &quot;{1}&quot;.
        /// </summary>
        internal static string Schedule_Day_Hour_Format {
            get {
                return ResourceManager.GetString("Schedule_Day_Hour_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soru.
        /// </summary>
        internal static string Sync_Question_Header {
            get {
                return ResourceManager.GetString("Sync_Question_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senkronizasyon işlemini başlayacaktır. Onaylıyormusunuz ?.
        /// </summary>
        internal static string Sync_Question_Message {
            get {
                return ResourceManager.GetString("Sync_Question_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senkronizasyon Uyarı !...
        /// </summary>
        internal static string Sync_Wrn_Header {
            get {
                return ResourceManager.GetString("Sync_Wrn_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cihazın bağlantısını ve tanımını kontrol ediniz..
        /// </summary>
        internal static string Sync_Wrn_Message {
            get {
                return ResourceManager.GetString("Sync_Wrn_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uyarı.
        /// </summary>
        internal static string TarihParam_UyarıBaslik {
            get {
                return ResourceManager.GetString("TarihParam_UyarıBaslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitiş tarihi başlangıç tarihinden büyük olmalıdır..
        /// </summary>
        internal static string TarihParam_UyarıMesaj {
            get {
                return ResourceManager.GetString("TarihParam_UyarıMesaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} alanı veri uzunluğu &apos;{1}&apos; karakteri geçemez..
        /// </summary>
        internal static string Validation_MaxLength {
            get {
                return ResourceManager.GetString("Validation_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} alanı zorunludur..
        /// </summary>
        internal static string Validation_Required {
            get {
                return ResourceManager.GetString("Validation_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} alanına girilen bilgi tekil olmalıdır..
        /// </summary>
        internal static string Validation_UniqueValue {
            get {
                return ResourceManager.GetString("Validation_UniqueValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hata.
        /// </summary>
        internal static string Validation_User_Caption {
            get {
                return ResourceManager.GetString("Validation_User_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Adı yada Parola Hatalı !...
        /// </summary>
        internal static string Validation_User_Text {
            get {
                return ResourceManager.GetString("Validation_User_Text", resourceCulture);
            }
        }
    }
}
